on:
  push:
    branches:
      - testboi-01
name: 🚀 Deploy testboi-01 on push to testboi-01
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER_TESTBOI_01 }}
        username: ${{ secrets.FTP_USERNAME_TESTBOI_01 }}
        password: ${{ secrets.FTP_PASSWORD_TESTBOI_01 }}
